#
# This is the main global crabgrass configuration.
#
# Most of the time, no other configuration should be required other than the
# options in this file. Unusual options might be configured elsewhere.
#
# For true/false and numeric values, you must not enclose the value in quotes.
#
# See doc/CONFIGURATION for more details.
#

##
## GLOBAL
##

enabled_languages:
  - en
  - fr
  - es
  - pt
  - ar
enabled_mods:
  - super_admin
  - moderation
  - unido
enabled_tools:
  - asset_tool
  - core_tools
  - event_tool
  - ranked_vote_tool
  - rate_many_tool
  - task_list_tool
  - wiki_tool
  - survey_tool
  - gallery_tool
  - external_video_tool
  - announcement_tool
  - feed_tool
email:
  delivery_method: :sendmail
#  smtp_settings:
#    domain: localhost
#    address: smtp.gmail.com
#    port: 587
#    authentication: :plain
#    user_name: xxxxxx@gmail.com
#    password: xxxxxxx

text_editor: html_only
##
## SITES
sites:
  - name: mru
    domain: my.MRUyouthplatform.org
    network: mru
    title: "MRU Youthplatform.org"
    limited: false
    email_sender: 'my@MRUyouthplatform.org'
    admin_group: superadmin
    moderation_group: "mru+ccmru"
    default: true
  - name: tvet
    domain: my.tvetplatform.org
    network: tvet
    title: "TVET Platform"
    limited: true
    email_sender: 'my@tvetplatform.org'
    default: false
    admin_group: tvet-admins
    moderation_group: tvet-moderators
  - name: unido
    domain: unido.mruyouthplatform.org
    network: unido
    title: "UNIDO Platform"
    limited: true
    email_sender: 'my@unidoplatform.org'
    default: false
    admin_group: unido-admins
    moderation_group: unido-admins
  - name: mdg
    domain: mdg.mruyouthplatform.org
    network: mdg
    title: "MDG Platform"
    limited: true
    email_sender: 'my@mdgplatform.org'
    default: false
    admin_group: mdg-admins
    moderation_group: mdg-admins
  - name: westafrica
    domain: westafrica.unidoplatform.org
    network: westafrica-site
    title: "Westafrica Platform"
    limited: true
    email_sender: 'my@westafrica.unidoplatform.org'
    default: false
    admin_group: westafrica-admins
    moderation_group: westafrica-mods

##
## SITE DEFAULTS
##

pagination_size: 30
default_language: en
enforce_ssl: false
show_exceptions: false
email_sender: "robot@$current_host"
tracking: true
available_page_types:
  - AssetPage
  - EventPage
  - ExternalVideoPage
  - TaskListPage
  - AnnouncementPage
  - SurveyPage
  - DiscussionPage
  - RateManyPage
  - MessagePage
  - RankedVotePage
  - ArticlePage
  - Gallery
  - WikiPage

