ME:
  Pages:
    My Work:
    All Pages:
    Trash:
  Social Activity:
    Friend Activity:
    Peer Activity:
  Messages:
  Tasks:
    Pending:  
      outside_nav: true
    Completed: 
      outside_nav: true
  Requests:
    Pending:
    Approved:
    Rejected:
  Profile:
    outside_nav: true
  Account:
    outside_nav: true
#  Logout:
#    outside_nav: true
PEOPLE:
  My Friends:
  All:
#    Stranger:
#      path: /stranger
GROUPS:
  My Groups:
    The Animals:
      outside_nav:true
      path: /animals
      Home:
        path: /animals
        People:
          path: /groups/people/animals
      Pages:
        path: /groups/pages/animals
      Tasks:
        path: /groups/tasks/animals
### this nav item is not showing up. 
### i'm creating a separate issue for it.
#      Administration:
#        path: /groups/animals/edit
#        Settings:
#          Basic Settings:
#            path: /groups/animals/edit
#          Permissions:
#            path: /groups/permissions/edit/animals
#          Public Profile:
#            path: /groups/profiles/edit/animals
#          Featured Pages:
#          Destroy Group:
#          Create Committee:
#        Requests:
  All Groups:  
NETWORKS:
  My Networks:
  All Networks:
